apiVersion: v1
kind: Service
metadata:
  name: guardshield-backend-service
  namespace: enterprise-demo
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: guardshield-api